version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: images
    volumes:
      - mysql-data:/var/lib/mysql

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db

  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: 123Soleil
    volumes:
      - neo4j-data:/data/databases

  commentaire:
    build: ./backend/commentaire
    ports:
      - "8080:8080"
    depends_on:
      - neo4j

  express:
    build: ./backend/connexion
    ports: 
      - 3000:3000  
    depends_on:
      - mongo

  post:
    build: ./backend/post
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  web:
    build: ./frontend
    ports:
      - "4200:4200"

volumes:
  mysql-data:
  mongo-data:
  neo4j-data: